# Successful object creation
mock_response_successful = {
    "service_id": "123e4567-e89b-12d3-a456-426614174000",
}

# Error Codes for SDXExceptions
mock_response_unsuccessful_400 = {
    "400": "Request does not have a valid JSON or body is incomplete/incorrect"
}
mock_response_unsuccessful_401 = {"401": "Not Authorized"}
mock_response_unsuccessful_402 = {
    "402": "Request not compatible (e.g., P2MP L2VPN requested, but only P2P supported)"
}
mock_response_unsuccessful_409 = {"409": "L2VPN Service already exists"}
mock_response_unsuccessful_410 = {"410": "Can't fulfill the strict QoS requirements"}
mock_response_unsuccessful_411 = {"411": "Scheduling not possible"}
mock_response_unsuccessful_422 = {"422": "Attribute not supported by the SDX-LC/OXPO"}
# Mock successful response
mock_response = {
    "service_id": "123e4567-e89b-12d3-a456-426614174000",
    "description": "L2VPN Service Modified",
}
# Define a mock response for no L2VPNs existing
mock_response_no_l2vpns = {}

# Define a mock response for one or more L2VPNs existing
mock_response_active_l2vpns_exist = {
    "c73da8e1-5d03-4620-a1db-7cdf23e8978c": {
        "service_id": "c73da8e1-5d03-4620-a1db-7cdf23e8978c",
        "name": "VLAN between AMPATH/300 and TENET/150",
        "endpoints": [
            {"port_id": "urn:sdx:port:tenet.ac.za:Tenet03:50", "vlan": "150"},
            {"port_id": "urn:sdx:port:sax.net:Sax02:50", "vlan": "400"},
            {"port_id": "urn:sdx:port:ampath.net:Ampath3:50", "vlan": "300"},
        ],
        "description": "Example 1",
        "qos_metrics": {
            "min_bw": {"value": 5, "strict": False},
            "max_delay": {"value": 150, "strict": True},
        },
        "notifications": [{"email": "user@domain.com"}, {"email": "user2@domain2.com"}],
        "ownership": "user1",
        "creation_date": "20240522T00:00:00Z",
        "archived_date": "0",
        "status": "up",
        "state": "enabled",
        "counters_location": "https://my.aw-sdx.net/l2vpn/7cdf23e8978c",
        "last_modified": "0",
        "current_path": ["urn:sdx:link:tenet.ac.za:LinkToAmpath"],
        "oxp_service_ids": {"ampath.net": ["c73da8e1"], "Tenet.ac.za": ["5d034620"]},
    },
    "fa2c99ca-30a9-4b51-8491-683c52e326a6": {
        "service_id": "fa2c99ca-30a9-4b51-8491-683c52e326a6",
        "name": "Example 2",
        "endpoints": [
            {"port_id": "urn:sdx:port:tenet.ac.za:Tenet03:50", "vlan": "3500"},
            {"port_id": "urn:sdx:port:sax.net:Sax01:50", "vlan": "3500"},
            {"port_id": "urn:sdx:port:ampath.net:Ampath3:50", "vlan": "3500"},
        ],
        "ownership": "user2",
        "creation_date": "20240422T00:00:00Z",
        "archived_date": "0",
        "status": "up",
        "state": "disabled",
        "counters_location": "https://my.aw-sdx.net/l2vpn/52e326a6",
        "last_modified": "0",
        "current_path": [
            "urn:sdx:link:tenet.ac.za:LinkToSAX",
            "urn:sdx:link:tenet.ac.za:LinkToAmpath",
            "urn:sdx:link:ampath.net:LinkToSAX",
        ],
        "oxp_service_ids": {
            "ampath.net": ["d82da7f9"],
            "tenet.ac.za": ["ab034673"],
            "sax.br": ["bb834633"],
        },
    },
}

# Define a mock response for one or more archived L2VPNs
mock_response_archived_l2vpns_exist = {
    "c73da8e1-5d03-4620-a1db-7cdf23e8978c": {
        "service_id": "c73da8e1-5d03-4620-a1db-7cdf23e8978c",
        "name": "VLAN between AMPATH/300 and TENET/150",
        "endpoints": [
            {"port_id": "urn:sdx:port:tenet.ac.za:Tenet03:50", "vlan": "150"},
            {"port_id": "urn:sdx:port:ampath.net:Ampath3:50", "vlan": "300"},
        ],
        "description": "Example 1",
        "qos_metrics": {
            "min_bw": {"value": 5, "strict": False},
            "max_delay": {"value": 150, "strict": True},
        },
        "notifications": [{"email": "user@domain.com"}, {"email": "user2@domain2.com"}],
        "ownership": "user1",
        "creation_date": "2024-05-22T00:00:00Z",
        "archived_date": "2024-06-16T19:20:30Z",
        "status": "up",
        "state": "enabled",
        "counters_location": "https://my.aw-sdx.net/l2vpn/7cdf23e8978c",
        "last_modified": "0",
        "current_path": ["urn:sdx:link:tenet.ac.za:LinkToAmpath"],
        "oxp_service_ids": {"ampath.net": ["c73da8e1"], "Tenet.ac.za": ["5d034620"]},
    },
    "fa2c99ca-30a9-4b51-8491-683c52e326a6": {
        "service_id": "fa2c99ca-30a9-4b51-8491-683c52e326a6",
        "name": "Example 2",
        "endpoints": [
            {"port_id": "urn:sdx:port:tenet.ac.za:Tenet03:50", "vlan": "3500"},
            {"port_id": "urn:sdx:port:sax.net:Sax01:50", "vlan": "3500"},
            {"port_id": "urn:sdx:port:ampath.net:Ampath3:50", "vlan": "3500"},
        ],
        "ownership": "user2",
        "creation_date": "2024-05-22T00:00:00Z",
        "archived_date": "2024-06-16T19:20:30Z",
        "status": "up",
        "state": "disabled",
        "counters_location": "https://my.aw-sdx.net/l2vpn/52e326a6",
        "last_modified": "0",
        "current_path": [
            "urn:sdx:link:tenet.ac.za:LinkToSAX",
            "urn:sdx:link:tenet.ac.za:LinkToAmpath",
            "urn:sdx:link:ampath.net:LinkToSAX",
        ],
        "oxp_service_ids": {
            "ampath.net": ["d82da7f9"],
            "tenet.ac.za": ["ab034673"],
            "sax.br": ["bb834633"],
        },
    },
}
mock_response_all_archived_l2vpns = {
    "c73da8e1-5d03-4620-a1db-7cdf23e8978c": {
        "service_id": "c73da8e1-5d03-4620-a1db-7cdf23e8978c",
        "name": "VLAN between AMPATH/300 and TENET/150",
        "endpoints": [
            {"port_id": "urn:sdx:port:tenet.ac.za:Tenet03:50", "vlan": "150"},
            {"port_id": "urn:sdx:port:ampath.net:Ampath3:50", "vlan": "300"},
        ],
        "description": "Example 1",
        "qos_metrics": {
            "min_bw": {"value": 5, "strict": False},
            "max_delay": {"value": 150, "strict": True},
        },
        "notifications": [{"email": "user@domain.com"}, {"email": "user2@domain2.com"}],
        "ownership": "user1",
        "creation_date": "2024-05-22T00:00:00Z",
        "archived_date": "0",
        "status": "up",
        "state": "enabled",
        "counters_location": "https://my.aw-sdx.net/l2vpn/7cdf23e8978c",
        "last_modified": "0",
        "current_path": ["urn:sdx:link:tenet.ac.za:LinkToAmpath"],
        "oxp_service_ids": {"ampath.net": ["c73da8e1"], "Tenet.ac.za": ["5d034620"]},
    },
    "fa2c99ca-30a9-4b51-8491-683c52e326a6": {
        "service_id": "fa2c99ca-30a9-4b51-8491-683c52e326a6",
        "name": "Example 2",
        "endpoints": [
            {"port_id": "urn:sdx:port:tenet.ac.za:Tenet03:50", "vlan": "3500"},
            {"port_id": "urn:sdx:port:sax.net:Sax01:50", "vlan": "3500"},
            {"port_id": "urn:sdx:port:ampath.net:Ampath3:50", "vlan": "3500"},
        ],
        "ownership": "user2",
        "creation_date": "2024-05-22T00:00:00Z",
        "archived_date": "2024-06-16T19:20:30Z",
        "status": "up",
        "state": "disabled",
        "counters_location": "https://my.aw-sdx.net/l2vpn/52e326a6",
        "last_modified": "0",
        "current_path": [
            "urn:sdx:link:tenet.ac.za:LinkToSAX",
            "urn:sdx:link:tenet.ac.za:LinkToAmpath",
            "urn:sdx:link:ampath.net:LinkToSAX",
        ],
        "oxp_service_ids": {
            "ampath.net": ["d82da7f9"],
            "tenet.ac.za": ["ab034673"],
            "sax.br": ["bb834633"],
        },
    },
}
# Define a mock response for one or more L2VPNs existing
mock_response_l2vpn_exists = {
    "c73da8e1-5d03-4620-a1db-7cdf23e8978c": {
        "service_id": "c73da8e1-5d03-4620-a1db-7cdf23e8978c",
        "name": "VLAN between AMPATH/300 and TENET/150",
        "endpoints": [
            {"port_id": "urn:sdx:port:tenet.ac.za:Tenet03:50", "vlan": "150"},
            {"port_id": "urn:sdx:port:ampath.net:Ampath3:50", "vlan": "300"},
        ],
        "description": "Example 1",
        "qos_metrics": {
            "min_bw": {"value": 5, "strict": False},
            "max_delay": {"value": 150, "strict": True},
        },
        "notifications": [{"email": "user@domain.com"}, {"email": "user2@domain2.com"}],
        "ownership": "user1",
        "creation_date": "20240522T00:00:00Z",
        "archived_date": "0",
        "status": "up",
        "state": "enabled",
        "counters_location": "https://my.aw-sdx.net/l2vpn/7cdf23e8978c",
        "last_modified": "0",
        "current_path": ["urn:sdx:link:tenet.ac.za:LinkToAmpath"],
        "oxp_service_ids": {"ampath.net": ["c73da8e1"], "Tenet.ac.za": ["5d034620"]},
    },
}

topology_1 = {
    "id": "urn:sdx:topology:amlight.net",
    "name": "Ampath-OXP",
    "services": ["l2vpn-ptp", "l2vpn-ptmp"],
    "version": 2,
    "model_version": "2.0.0",
    "timestamp": "2025-02-21T15:09:21Z",
    "nodes": [
        {
            "id": "urn:sdx:node:ampath.net:Ampath3",
            "name": "Ampath3",
            "status": "up",
            "state": "enabled",
            "location": {
                "address": "Jacksonville",
                "latitude": "30.27",
                "longitude": "-81.68",
                "iso3166_2_lvl4": "US-FL",
            },
            "ports": [
                {
                    "id": "urn:sdx:port:ampath.net:Ampath3:2",
                    "name": "Ampath3-eth2",
                    "node": "urn:sdx:node:ampath.net:Ampath3",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:ampath.net:Ampath1/2_Ampath3/2",
                    "type": "10GE",
                    "entities": ["FIU", "WOW", "Wall of Wind"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                    "private": ["residual_bandwidth", "latency", "packet_loss"],
                },
                {
                    "id": "urn:sdx:port:ampath.net:Ampath3:50",
                    "name": "Ampath3-eth50",
                    "node": "urn:sdx:node:ampath.net:Ampath3",
                    "status": "up",
                    "state": "enabled",
                    "nni": "",
                    "entities": ["Disney World", "University of Florida", "MIT"],
                    "type": "10GE",
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:ampath.net:Ampath3:3",
                    "name": "Ampath3-eth3",
                    "node": "urn:sdx:node:ampath.net:Ampath3",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:ampath.net:Ampath2/3_Ampath3/3",
                    "entities": ["Indiana University", "IU"],
                    "type": "10GE",
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
            ],
        },
        {
            "id": "urn:sdx:node:ampath.net:Ampath2",
            "name": "Ampath2",
            "status": "up",
            "state": "enabled",
            "location": {
                "address": "BocaRaton",
                "latitude": "26.38",
                "longitude": "-80.11",
                "iso3166_2_lvl4": "US-FL",
            },
            "ports": [
                {
                    "id": "urn:sdx:port:ampath.net:Ampath2:1",
                    "name": "Ampath2-eth1",
                    "node": "urn:sdx:node:ampath.net:Ampath2",
                    "status": "up",
                    "state": "enabled",
                    "entities": ["Brazil", "TTU", "South America"],
                    "nni": "urn:sdx:link:ampath.net:Ampath1/1_Ampath2/1",
                    "type": "10GE",
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:ampath.net:Ampath2:50",
                    "name": "Ampath2-eth50",
                    "node": "urn:sdx:node:ampath.net:Ampath2",
                    "status": "up",
                    "state": "enabled",
                    "nni": "",
                    "type": "10GE",
                    "entities": ["NCSA", "UIUC", "University of Illinois"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:ampath.net:Ampath2:40",
                    "name": "Ampath2-eth40",
                    "node": "urn:sdx:node:ampath.net:Ampath2",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:port:sax.net:Sax02:40",
                    "type": "10GE",
                    "entities": ["Something Random", "Miami Beach"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:ampath.net:Ampath2:3",
                    "name": "Ampath2-eth3",
                    "node": "urn:sdx:node:ampath.net:Ampath2",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:ampath.net:Ampath2/3_Ampath3/3",
                    "type": "10GE",
                    "entities": ["Vanderbilt", "Princeton", "Harvard"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
            ],
        },
        {
            "id": "urn:sdx:node:ampath.net:Ampath1",
            "name": "Ampath1",
            "status": "up",
            "state": "enabled",
            "location": {
                "address": "Miami",
                "latitude": "25.77",
                "longitude": "-80.19",
                "iso3166_2_lvl4": "US-FL",
            },
            "ports": [
                {
                    "id": "urn:sdx:port:ampath.net:Ampath1:1",
                    "name": "Ampath1-eth1",
                    "node": "urn:sdx:node:ampath.net:Ampath1",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:ampath.net:Ampath1/1_Ampath2/1",
                    "type": "10GE",
                    "entities": ["South America", "Universidad De Brazil"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:ampath.net:Ampath1:40",
                    "name": "Ampath1-eth40",
                    "node": "urn:sdx:node:ampath.net:Ampath1",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:port:sax.net:Sax01:40",
                    "type": "10GE",
                    "entities": ["Africa", "South Africa", "Cape Town"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:ampath.net:Ampath1:50",
                    "name": "Ampath1-eth50",
                    "node": "urn:sdx:node:ampath.net:Ampath1",
                    "status": "up",
                    "state": "enabled",
                    "nni": "",
                    "type": "10GE",
                    "entities": ["Canada", "New York", "University"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:ampath.net:Ampath1:2",
                    "name": "Ampath1-eth2",
                    "node": "urn:sdx:node:ampath.net:Ampath1",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:ampath.net:Ampath1/2_Ampath3/2",
                    "type": "10GE",
                    "entities": ["NYU", "New York", "Tenet"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
            ],
        },
        {
            "id": "urn:sdx:node:sax.net:Sax01",
            "name": "Sax01",
            "status": "up",
            "state": "enabled",
            "location": {
                "address": "Fortaleza",
                "latitude": "-3",
                "longitude": "-40",
                "iso3166_2_lvl4": "BR-CE",
            },
            "ports": [
                {
                    "id": "urn:sdx:port:sax.net:Sax01:41",
                    "name": "Sax01-eth41",
                    "node": "urn:sdx:node:sax.net:Sax01",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:port:tenet.ac.za:Tenet01:41",
                    "type": "10GE",
                    "entities": [],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:sax.net:Sax01:1",
                    "name": "Sax01-eth1",
                    "node": "urn:sdx:node:sax.net:Sax01",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:sax.net:Sax01/1_Sax02/1",
                    "type": "10GE",
                    "entities": ["Sao Paulo"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:sax.net:Sax01:40",
                    "name": "Sax01-eth40",
                    "node": "urn:sdx:node:sax.net:Sax01",
                    "status": "up",
                    "state": "enabled",
                    "entities": ["Sao Paulo", "Ampath"],
                    "nni": "urn:sdx:port:ampath.net:Ampath1:40",
                    "type": "10GE",
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:sax.net:Sax01:50",
                    "name": "Sax01-eth50",
                    "node": "urn:sdx:node:sax.net:Sax01",
                    "status": "up",
                    "state": "enabled",
                    "nni": "",
                    "type": "10GE",
                    "entities": ["France", "Cern"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
            ],
        },
        {
            "id": "urn:sdx:node:sax.net:Sax02",
            "name": "Sax02",
            "status": "up",
            "state": "enabled",
            "location": {
                "address": "Fortaleza",
                "latitude": "-3",
                "longitude": "-20",
                "iso3166_2_lvl4": "BR-CE",
            },
            "ports": [
                {
                    "id": "urn:sdx:port:sax.net:Sax02:41",
                    "name": "Sax02-eth41",
                    "node": "urn:sdx:node:sax.net:Sax02",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:port:tenet.ac.za:Tenet02:41",
                    "type": "10GE",
                    "entities": [
                        "TTU",
                        "Tennessee Tech Univ",
                        "TN Tech University",
                        "Cookeville",
                    ],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:sax.net:Sax02:1",
                    "name": "Sax02-eth1",
                    "node": "urn:sdx:node:sax.net:Sax02",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:sax.net:Sax01/1_Sax02/1",
                    "type": "10GE",
                    "entities": [
                        "FIU",
                        "Florida International Unitversity",
                        "Miami",
                        "florida international university",
                        "florida national university",
                        "florida technology university",
                    ],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:sax.net:Sax02:40",
                    "name": "Sax02-eth40",
                    "node": "urn:sdx:node:sax.net:Sax02",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:port:ampath.net:Ampath2:40",
                    "type": "10GE",
                    "entities": [
                        "MIT",
                        "Massachusetts Institute of Technology",
                        "Cambridge",
                    ],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:sax.net:Sax02:50",
                    "name": "Sax02-eth50",
                    "node": "urn:sdx:node:sax.net:Sax02",
                    "status": "up",
                    "state": "enabled",
                    "nni": "",
                    "type": "10GE",
                    "entities": [
                        "UCLA",
                        "University of California, Los Angeles",
                        "Los Angeles",
                    ],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
            ],
        },
        {
            "id": "urn:sdx:node:tenet.ac.za:Tenet02",
            "name": "Tenet02",
            "status": "up",
            "state": "enabled",
            "location": {
                "address": "Johanesburgo",
                "latitude": "-26",
                "longitude": "28",
                "iso3166_2_lvl4": "ZA-GP",
            },
            "ports": [
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet02:41",
                    "name": "Tenet02-eth41",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet02",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:port:sax.net:Sax02:41",
                    "type": "10GE",
                    "entities": ["UT", "University of Texas", "Austin"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet02:1",
                    "name": "Tenet02-eth1",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet02",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:tenet.ac.za:Tenet01/1_Tenet02/1",
                    "type": "10GE",
                    "entities": ["OSU", "Ohio State University", "Columbus"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet02:50",
                    "name": "Tenet02-eth50",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet02",
                    "status": "up",
                    "state": "enabled",
                    "nni": "",
                    "type": "10GE",
                    "entities": ["FSU", "Florida State University", "Tallahassee"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
            ],
        },
        {
            "id": "urn:sdx:node:tenet.ac.za:Tenet03",
            "name": "Tenet03",
            "status": "up",
            "state": "enabled",
            "location": {
                "address": "EastLondon",
                "latitude": "-33",
                "longitude": "27",
                "iso3166_2_lvl4": "ZA-EC",
            },
            "ports": [
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet03:50",
                    "name": "Tenet03-eth50",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet03",
                    "status": "up",
                    "state": "enabled",
                    "nni": "",
                    "type": "10GE",
                    "entities": ["NYU", "New York University", "New York City"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet03:2",
                    "name": "Tenet03-eth2",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet03",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:tenet.ac.za:Tenet01/2_Tenet03/2",
                    "type": "10GE",
                    "entities": ["UF", "University of Florida", "Gainesville"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
            ],
        },
        {
            "id": "urn:sdx:node:tenet.ac.za:Tenet01",
            "name": "Tenet01",
            "status": "up",
            "state": "enabled",
            "location": {
                "address": "CapeTown",
                "latitude": "-33",
                "longitude": "18",
                "iso3166_2_lvl4": "ZA-WC",
            },
            "ports": [
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet01:41",
                    "name": "Tenet01-eth41",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet01",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:port:sax.net:Sax01:41",
                    "type": "10GE",
                    "entities": [
                        "USC",
                        "University of Southern California",
                        "Los Angeles",
                    ],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet01:1",
                    "name": "Tenet01-eth1",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet01",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:tenet.ac.za:Tenet01/1_Tenet02/1",
                    "type": "10GE",
                    "entities": ["CU", "Columbia University", "New York City"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet01:2",
                    "name": "Tenet01-eth2",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet01",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:tenet.ac.za:Tenet01/2_Tenet03/2",
                    "type": "10GE",
                    "entities": ["Duke", "Duke University", "Durham"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet01:50",
                    "name": "Tenet01-eth50",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet01",
                    "status": "up",
                    "state": "enabled",
                    "nni": "",
                    "type": "10GE",
                    "entities": ["GT", "Georgia Tech", "Atlanta"],
                    "services": {
                        "l2vpn-ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn-ptmp": {},
                    },
                },
            ],
        },
    ],
    "links": [
        {
            "id": "urn:sdx:link:ampath.net:Ampath0",
            # "id": "urn:sdx:link:interdomain:ampath.net:Ampath1:40:sax.net:Sax01:40",
            "name": "Ampath1-eth40--Sax01-eth40",
            "ports": [
                "urn:sdx:port:ampath.net:Ampath1:40",
                "urn:sdx:port:sax.net:Sax01:40",
            ],
            "type": "intra",
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 100,
            "status": "up",
            "state": "enabled",
            "private": [],
        },
        {
            "id": "urn:sdx:link:ampath.net:Ampath3",
            "name": "Ampath2-eth40--Sax02-eth40",
            "ports": [
                "urn:sdx:port:ampath.net:Ampath2:40",
                "urn:sdx:port:sax.net:Sax02:40",
            ],
            "type": "intra",
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 100,
            "status": "up",
            "state": "enabled",
            "private": [],
        },
        {
            "id": "urn:sdx:link:ampath.net:Ampath2",
            "name": "Sax02-eth41--Tenet02-eth41",
            "ports": [
                "urn:sdx:port:sax.net:Sax02:41",
                "urn:sdx:port:tenet.ac.za:Tenet02:41",
            ],
            "type": "intra",
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 100,
            "status": "up",
            "state": "enabled",
            "private": [],
        },
        {
            "id": "urn:sdx:link:ampath.net:Ampath1",
            "name": "Sax01-eth41--Tenet01-eth41",
            "ports": [
                "urn:sdx:port:sax.net:Sax01:41",
                "urn:sdx:port:tenet.ac.za:Tenet01:41",
            ],
            "type": "intra",
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 100,
            "status": "up",
            "state": "enabled",
            "private": [],
        },
        {
            "id": "urn:sdx:link:ampath.net:Ampath2/3_Ampath3/3",
            "name": "Ampath2/3_Ampath3/3",
            "ports": [
                "urn:sdx:port:ampath.net:Ampath2:3",
                "urn:sdx:port:ampath.net:Ampath3:3",
            ],
            "type": "intra",
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 100,
            "status": "up",
            "state": "enabled",
            "private": [],
        },
        {
            "id": "urn:sdx:link:ampath.net:Ampath1/2_Ampath3/2",
            "name": "Ampath1/2_Ampath3/2",
            "ports": [
                "urn:sdx:port:ampath.net:Ampath1:2",
                "urn:sdx:port:ampath.net:Ampath3:2",
            ],
            "type": "intra",
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 100,
            "status": "up",
            "state": "enabled",
            "private": [],
        },
        {
            "id": "urn:sdx:link:ampath.net:Ampath1/1_Ampath2/1",
            "name": "Ampath1/1_Ampath2/1",
            "ports": [
                "urn:sdx:port:ampath.net:Ampath1:1",
                "urn:sdx:port:ampath.net:Ampath2:1",
            ],
            "type": "intra",
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 100,
            "status": "up",
            "state": "enabled",
            "private": [],
        },
        {
            "id": "urn:sdx:link:sax.net:Sax01/1_Sax02/1",
            "name": "Sax01/1_Sax02/1",
            "ports": ["urn:sdx:port:sax.net:Sax01:1", "urn:sdx:port:sax.net:Sax02:1"],
            "type": "intra",
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 100,
            "status": "up",
            "state": "enabled",
            "private": [],
        },
        {
            "id": "urn:sdx:link:tenet.ac.za:Tenet01/1_Tenet02/1",
            "name": "Tenet01/1_Tenet02/1",
            "ports": [
                "urn:sdx:port:tenet.ac.za:Tenet01:1",
                "urn:sdx:port:tenet.ac.za:Tenet02:1",
            ],
            "type": "intra",
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 100,
            "status": "up",
            "state": "enabled",
            "private": [],
        },
        {
            "id": "urn:sdx:link:tenet.ac.za:Tenet01/2_Tenet03/2",
            "name": "Tenet01/2_Tenet03/2",
            "ports": [
                "urn:sdx:port:tenet.ac.za:Tenet01:2",
                "urn:sdx:port:tenet.ac.za:Tenet03:2",
            ],
            "type": "intra",
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 100,
            "status": "up",
            "state": "enabled",
            "private": [],
        },
    ],
}


# topology = {
#     "id": "urn:sdx:topology:",
#     "name": "Ampath-OXP",
#     "services": {
#         "l2vpn_ptp": "l2vpn-ptp",
#         "l2vpn_ptmp": [null],
#         "monitoring_capability": null,
#         "owner": null,
#         "private_attributes": null,
#         "provisioning_system": null,
#         "provisioning_url": null,
#         "vendor": null,
#     },
#     "version": "3.0",
#     "model_version": null,
#     "timestamp": "2025-02-26T21:30:32.592362",
#     "nodes": [
#         {
#             "id": "urn:sdx:node:ampath.net:Novi03",
#             "name": "Novi03",
#             "short_name": null,
#             "status": "up",
#             "state": "enabled",
#             "location": {
#                 "address": "BocaRaton",
#                 "latitude": 26.38,
#                 "longitude": -80.11,
#                 "iso3166_2_lvl4": "US-FL",
#             },
#             "ports": [
#                 {
#                     "id": "urn:sdx:port:ampath.net:Novi03:1",
#                     "name": "Novi03-eth1",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:ampath.net:Novi03",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "urn:sdx:port:tenet.ac.za:Novi07:1",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:ampath.net:Novi03:5",
#                     "name": "Novi03-eth5",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:ampath.net:Novi03",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:ampath.net:Novi03:3",
#                     "name": "Novi03-eth3",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:ampath.net:Novi03",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#             ],
#             "private_attributes": [],
#         },
#         {
#             "id": "urn:sdx:node:ampath.net:Novi01",
#             "name": "Novi01",
#             "short_name": null,
#             "status": "up",
#             "state": "enabled",
#             "location": {
#                 "address": "Miami",
#                 "latitude": 25.77,
#                 "longitude": -80.19,
#                 "iso3166_2_lvl4": "US-FL",
#             },
#             "ports": [
#                 {
#                     "id": "urn:sdx:port:ampath.net:Novi01:11",
#                     "name": "Novi01-eth11",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:ampath.net:Novi01",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:ampath.net:Novi01:1",
#                     "name": "Novi01-eth1",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:ampath.net:Novi01",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "urn:sdx:port:tenet.ac.za:Novi06:1",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:ampath.net:Novi01:2",
#                     "name": "Novi01-eth2",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:ampath.net:Novi01",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:ampath.net:Novi01:3",
#                     "name": "Novi01-eth3",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:ampath.net:Novi01",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#             ],
#             "private_attributes": [],
#         },
#         {
#             "id": "urn:sdx:node:ampath.net:Novi02",
#             "name": "Novi02",
#             "short_name": null,
#             "status": "up",
#             "state": "enabled",
#             "location": {
#                 "address": "BocaRaton",
#                 "latitude": 26.38,
#                 "longitude": -80.11,
#                 "iso3166_2_lvl4": "US-FL",
#             },
#             "ports": [
#                 {
#                     "id": "urn:sdx:port:ampath.net:Novi02:22",
#                     "name": "Novi02-eth22",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:ampath.net:Novi02",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:ampath.net:Novi02:4",
#                     "name": "Novi02-eth4",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:ampath.net:Novi02",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "urn:sdx:port:sax.net:Novi04:4",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:ampath.net:Novi02:5",
#                     "name": "Novi02-eth5",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:ampath.net:Novi02",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:ampath.net:Novi02:2",
#                     "name": "Novi02-eth2",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:ampath.net:Novi02",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:ampath.net:Novi02:3",
#                     "name": "Novi02-eth3",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:ampath.net:Novi02",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "urn:sdx:port:tenet.ac.za:Novi06:3",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#             ],
#             "private_attributes": [],
#         },
#         {
#             "id": "urn:sdx:node:sax.net:Novi04",
#             "name": "Novi04",
#             "short_name": null,
#             "status": "up",
#             "state": "enabled",
#             "location": {
#                 "address": "Fortaleza",
#                 "latitude": -3.0,
#                 "longitude": -40.0,
#                 "iso3166_2_lvl4": "BR-CE",
#             },
#             "ports": [
#                 {
#                     "id": "urn:sdx:port:sax.net:Novi04:4",
#                     "name": "Novi04-eth4",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:sax.net:Novi04",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "urn:sdx:port:ampath.net:Novi02:4",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": ["1-4095"]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:sax.net:Novi04:6",
#                     "name": "Novi04-eth6",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:sax.net:Novi04",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": ["1-4095"]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#             ],
#             "private_attributes": [],
#         },
#         {
#             "id": "urn:sdx:node:sax.net:Novi05",
#             "name": "Novi05",
#             "short_name": null,
#             "status": "up",
#             "state": "enabled",
#             "location": {
#                 "address": "Fortaleza",
#                 "latitude": -3.0,
#                 "longitude": -20.0,
#                 "iso3166_2_lvl4": "BR-CE",
#             },
#             "ports": [
#                 {
#                     "id": "urn:sdx:port:sax.net:Novi05:6",
#                     "name": "Novi05-eth6",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:sax.net:Novi05",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": ["1-4095"]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:sax.net:Novi05:7",
#                     "name": "Novi05-eth7",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:sax.net:Novi05",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "urn:sdx:port:tenet.ac.za:Novi06:7",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": ["1-4095"]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#             ],
#             "private_attributes": [],
#         },
#         {
#             "id": "urn:sdx:node:tenet.ac.za:Novi08",
#             "name": "Novi08",
#             "short_name": null,
#             "status": "up",
#             "state": "enabled",
#             "location": {
#                 "address": "Johanesburgo",
#                 "latitude": -26.0,
#                 "longitude": 28.0,
#                 "iso3166_2_lvl4": "ZA-GP",
#             },
#             "ports": [
#                 {
#                     "id": "urn:sdx:port:tenet.ac.za:Novi08:44",
#                     "name": "Novi08-eth44",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:tenet.ac.za:Novi08",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": ["1-4095"]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:tenet.ac.za:Novi08:9",
#                     "name": "Novi08-eth9",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:tenet.ac.za:Novi08",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": ["1-4095"]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#             ],
#             "private_attributes": [],
#         },
#         {
#             "id": "urn:sdx:node:tenet.ac.za:Novi07",
#             "name": "Novi07",
#             "short_name": null,
#             "status": "up",
#             "state": "enabled",
#             "location": {
#                 "address": "Johanesburgo",
#                 "latitude": -26.0,
#                 "longitude": 28.0,
#                 "iso3166_2_lvl4": "ZA-GP",
#             },
#             "ports": [
#                 {
#                     "id": "urn:sdx:port:tenet.ac.za:Novi07:33",
#                     "name": "Novi07-eth33",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:tenet.ac.za:Novi07",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": ["1-4095"]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:tenet.ac.za:Novi07:8",
#                     "name": "Novi07-eth8",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:tenet.ac.za:Novi07",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": ["1-4095"]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:tenet.ac.za:Novi07:1",
#                     "name": "Novi07-eth1",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:tenet.ac.za:Novi07",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "urn:sdx:port:ampath.net:Novi03:1",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": ["1-4095"]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:tenet.ac.za:Novi07:9",
#                     "name": "Novi07-eth9",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:tenet.ac.za:Novi07",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": ["1-4095"]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#             ],
#             "private_attributes": [],
#         },
#         {
#             "id": "urn:sdx:node:tenet.ac.za:Novi06",
#             "name": "Novi06",
#             "short_name": null,
#             "status": "up",
#             "state": "enabled",
#             "location": {
#                 "address": "CapeTown",
#                 "latitude": -33.0,
#                 "longitude": 18.0,
#                 "iso3166_2_lvl4": "ZA-WC",
#             },
#             "ports": [
#                 {
#                     "id": "urn:sdx:port:tenet.ac.za:Novi06:7",
#                     "name": "Novi06-eth7",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:tenet.ac.za:Novi06",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "urn:sdx:port:sax.net:Novi05:7",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": ["1-4095"]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:tenet.ac.za:Novi06:1",
#                     "name": "Novi06-eth1",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:tenet.ac.za:Novi06",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "urn:sdx:port:ampath.net:Novi01:1",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": ["1-4095"]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:tenet.ac.za:Novi06:8",
#                     "name": "Novi06-eth8",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:tenet.ac.za:Novi06",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": ["1-4095"]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#                 {
#                     "id": "urn:sdx:port:tenet.ac.za:Novi06:3",
#                     "name": "Novi06-eth3",
#                     "entities": null,
#                     "short_name": null,
#                     "node": "urn:sdx:node:tenet.ac.za:Novi06",
#                     "vlan_range": null,
#                     "status": "up",
#                     "state": "enabled",
#                     "nni": "urn:sdx:port:ampath.net:Novi02:3",
#                     "type": "10GE",
#                     "services": {
#                         "l2vpn_ptp": {"vlan_range": ["1-4095"]},
#                         "l2vpn_ptmp": {},
#                         "monitoring_capability": null,
#                         "owner": null,
#                         "private_attributes": null,
#                         "provisioning_system": null,
#                         "provisioning_url": null,
#                         "vendor": null,
#                     },
#                     "private_attributes": null,
#                 },
#             ],
#             "private_attributes": [],
#         },
#     ],
#     "links": [
#         {
#             "id": "urn:sdx:link:ampath.net:Novi02-eth2_Novi01-eth2",
#             "name": "Novi02-eth2_Novi01-eth2",
#             "short_name": null,
#             "ports": [
#                 "urn:sdx:port:ampath.net:Novi02:2",
#                 "urn:sdx:port:ampath.net:Novi01:2",
#             ],
#             "bandwidth": 10,
#             "residual_bandwidth": 100,
#             "latency": 2,
#             "packet_loss": 0,
#             "availability": null,
#             "status": "error",
#             "state": "disabled",
#             "private_attributes": null,
#             "timestamp": null,
#             "measurement_period": null,
#         },
#         {
#             "id": "urn:sdx:link:sax.net:Novi04-eth6_Novi05-eth6",
#             "name": "Novi04-eth6_Novi05-eth6",
#             "short_name": null,
#             "ports": ["urn:sdx:port:sax.net:Novi04:6", "urn:sdx:port:sax.net:Novi05:6"],
#             "bandwidth": 10,
#             "residual_bandwidth": 100,
#             "latency": 2,
#             "packet_loss": 0,
#             "availability": null,
#             "status": "error",
#             "state": "disabled",
#             "private_attributes": null,
#             "timestamp": null,
#             "measurement_period": null,
#         },
#         {
#             "id": "urn:sdx:link:interdomain:ampath.net:Novi02:4:sax.net:Novi04:4",
#             "name": "Novi02-eth4--Novi04-eth4",
#             "short_name": null,
#             "ports": [
#                 "urn:sdx:port:ampath.net:Novi02:4",
#                 "urn:sdx:port:sax.net:Novi04:4",
#             ],
#             "bandwidth": 10,
#             "residual_bandwidth": 100,
#             "latency": 0,
#             "packet_loss": 0,
#             "availability": 100,
#             "status": "up",
#             "state": "enabled",
#             "private_attributes": null,
#             "timestamp": null,
#             "measurement_period": null,
#         },
#         {
#             "id": "urn:sdx:link:tenet.ac.za:Novi08-eth9_Novi07-eth9",
#             "name": "Novi08-eth9_Novi07-eth9",
#             "short_name": null,
#             "ports": [
#                 "urn:sdx:port:tenet.ac.za:Novi08:9",
#                 "urn:sdx:port:tenet.ac.za:Novi07:9",
#             ],
#             "bandwidth": 10,
#             "residual_bandwidth": 100,
#             "latency": 2,
#             "packet_loss": 0,
#             "availability": null,
#             "status": "error",
#             "state": "disabled",
#             "private_attributes": null,
#             "timestamp": null,
#             "measurement_period": null,
#         },
#         {
#             "id": "urn:sdx:link:tenet.ac.za:Novi06-eth8_Novi07-eth8",
#             "name": "Novi06-eth8_Novi07-eth8",
#             "short_name": null,
#             "ports": [
#                 "urn:sdx:port:tenet.ac.za:Novi06:8",
#                 "urn:sdx:port:tenet.ac.za:Novi07:8",
#             ],
#             "bandwidth": 10,
#             "residual_bandwidth": 100,
#             "latency": 2,
#             "packet_loss": 0,
#             "availability": null,
#             "status": "error",
#             "state": "disabled",
#             "private_attributes": null,
#             "timestamp": null,
#             "measurement_period": null,
#         },
#         {
#             "id": "urn:sdx:link:interdomain:ampath.net:Novi03:1:tenet.ac.za:Novi07:1",
#             "name": "Novi03-eth1--Novi07-eth1",
#             "short_name": null,
#             "ports": [
#                 "urn:sdx:port:ampath.net:Novi03:1",
#                 "urn:sdx:port:tenet.ac.za:Novi07:1",
#             ],
#             "bandwidth": 10,
#             "residual_bandwidth": 100.0,
#             "latency": 0,
#             "packet_loss": 0,
#             "availability": 100,
#             "status": "up",
#             "state": "enabled",
#             "private_attributes": null,
#             "timestamp": null,
#             "measurement_period": null,
#         },
#         {
#             "id": "urn:sdx:link:interdomain:sax.net:Novi05:7:tenet.ac.za:Novi06:7",
#             "name": "Novi05-eth7--Novi06-eth7",
#             "short_name": null,
#             "ports": [
#                 "urn:sdx:port:sax.net:Novi05:7",
#                 "urn:sdx:port:tenet.ac.za:Novi06:7",
#             ],
#             "bandwidth": 10,
#             "residual_bandwidth": 100,
#             "latency": 0,
#             "packet_loss": 0,
#             "availability": 100,
#             "status": "up",
#             "state": "enabled",
#             "private_attributes": null,
#             "timestamp": null,
#             "measurement_period": null,
#         },
#         {
#             "id": "urn:sdx:link:interdomain:ampath.net:Novi01:1:tenet.ac.za:Novi06:1",
#             "name": "Novi01-eth1--Novi06-eth1",
#             "short_name": null,
#             "ports": [
#                 "urn:sdx:port:ampath.net:Novi01:1",
#                 "urn:sdx:port:tenet.ac.za:Novi06:1",
#             ],
#             "bandwidth": 10,
#             "residual_bandwidth": 100,
#             "latency": 0,
#             "packet_loss": 0,
#             "availability": 100,
#             "status": "up",
#             "state": "enabled",
#             "private_attributes": null,
#             "timestamp": null,
#             "measurement_period": null,
#         },
#         {
#             "id": "urn:sdx:link:interdomain:ampath.net:Novi02:3:tenet.ac.za:Novi06:3",
#             "name": "Novi02-eth3--Novi06-eth3",
#             "short_name": null,
#             "ports": [
#                 "urn:sdx:port:ampath.net:Novi02:3",
#                 "urn:sdx:port:tenet.ac.za:Novi06:3",
#             ],
#             "bandwidth": 10,
#             "residual_bandwidth": 100,
#             "latency": 0,
#             "packet_loss": 0,
#             "availability": 100,
#             "status": "up",
#             "state": "enabled",
#             "private_attributes": null,
#             "timestamp": null,
#             "measurement_period": null,
#         },
#         {
#             "id": "urn:sdx:link:ampath.net:Novi03-eth5_Novi02-eth5",
#             "name": "Novi03-eth5_Novi02-eth5",
#             "short_name": null,
#             "ports": [
#                 "urn:sdx:port:ampath.net:Novi03:5",
#                 "urn:sdx:port:ampath.net:Novi02:5",
#             ],
#             "bandwidth": 10,
#             "residual_bandwidth": 100,
#             "latency": 2,
#             "packet_loss": 0,
#             "availability": null,
#             "status": "error",
#             "state": "disabled",
#             "private_attributes": null,
#             "timestamp": null,
#             "measurement_period": null,
#         },
#         {
#             "id": "urn:sdx:link:ampath.net:Novi01-eth2_Novi02-eth2",
#             "name": "Novi01-eth2_Novi02-eth2",
#             "short_name": null,
#             "ports": [
#                 "urn:sdx:port:ampath.net:Novi01:2",
#                 "urn:sdx:port:ampath.net:Novi02:2",
#             ],
#             "bandwidth": 10,
#             "residual_bandwidth": 100,
#             "latency": 2,
#             "packet_loss": 0,
#             "availability": null,
#             "status": "error",
#             "state": "disabled",
#             "private_attributes": null,
#             "timestamp": null,
#             "measurement_period": null,
#         },
#         {
#             "id": "urn:sdx:link:ampath.net:Novi03-eth3_Novi01-eth3",
#             "name": "Novi03-eth3_Novi01-eth3",
#             "short_name": null,
#             "ports": [
#                 "urn:sdx:port:ampath.net:Novi03:3",
#                 "urn:sdx:port:ampath.net:Novi01:3",
#             ],
#             "bandwidth": 10,
#             "residual_bandwidth": 100,
#             "latency": 2,
#             "packet_loss": 0,
#             "availability": null,
#             "status": "error",
#             "state": "disabled",
#             "private_attributes": null,
#             "timestamp": null,
#             "measurement_period": null,
#         },
#     ],
#     "private_attributes": null,
# }
