[project]
name = "sdx-lib"
version = "0.36.1"
description = "Local module for AW-SDX"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"

