{
    "id": "urn:sdx:topology:",
    "name": "Ampath-OXP",
    "services": {
        "l2vpn_ptp": "l2vpn-ptp",
        "l2vpn_ptmp": ["null"],
        "monitoring_capability": "null",
        "owner": "null",
        "private_attributes": "null",
        "provisioning_system": "null",
        "provisioning_url": "null",
        "vendor": "null",
    },
    "version": "2.6",
    "model_version": "null",
    "timestamp": "2025-02-21T15:09:21.411954",
    "nodes": [
        {
            "id": "urn:sdx:node:ampath.net:Ampath3",
            "name": "Ampath3",
            "short_name": "null",
            "location": {
                "address": "Jacksonville",
                "latitude": 30.27,
                "longitude": -81.68,
                "iso3166_2_lvl4": "US-FL",
            },
            "ports": [
                {
                    "id": "urn:sdx:port:ampath.net:Ampath3:2",
                    "name": "Ampath3-eth2",
                    "short_name": "null",
                    "node": "urn:sdx:node:ampath.net:Ampath3",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:ampath.net:Ampath1/2_Ampath3/2",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:ampath.net:Ampath3:50",
                    "name": "Ampath3-eth50",
                    "short_name": "null",
                    "node": "urn:sdx:node:ampath.net:Ampath3",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:ampath.net:Ampath3:3",
                    "name": "Ampath3-eth3",
                    "short_name": "null",
                    "node": "urn:sdx:node:ampath.net:Ampath3",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:ampath.net:Ampath2/3_Ampath3/3",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
            ],
            "private_attributes": [],
        },
        {
            "id": "urn:sdx:node:ampath.net:Ampath2",
            "name": "Ampath2",
            "short_name": "null",
            "location": {
                "address": "BocaRaton",
                "latitude": 26.38,
                "longitude": -80.11,
                "iso3166_2_lvl4": "US-FL",
            },
            "ports": [
                {
                    "id": "urn:sdx:port:ampath.net:Ampath2:1",
                    "name": "Ampath2-eth1",
                    "short_name": "null",
                    "node": "urn:sdx:node:ampath.net:Ampath2",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:ampath.net:Ampath1/1_Ampath2/1",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:ampath.net:Ampath2:50",
                    "name": "Ampath2-eth50",
                    "short_name": "null",
                    "node": "urn:sdx:node:ampath.net:Ampath2",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:ampath.net:Ampath2:40",
                    "name": "Ampath2-eth40",
                    "short_name": "null",
                    "node": "urn:sdx:node:ampath.net:Ampath2",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:port:sax.net:Sax02:40",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:ampath.net:Ampath2:3",
                    "name": "Ampath2-eth3",
                    "short_name": "null",
                    "node": "urn:sdx:node:ampath.net:Ampath2",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:ampath.net:Ampath2/3_Ampath3/3",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
            ],
            "private_attributes": [],
        },
        {
            "id": "urn:sdx:node:ampath.net:Ampath1",
            "name": "Ampath1",
            "short_name": "null",
            "location": {
                "address": "Miami",
                "latitude": 25.77,
                "longitude": -80.19,
                "iso3166_2_lvl4": "US-FL",
            },
            "ports": [
                {
                    "id": "urn:sdx:port:ampath.net:Ampath1:1",
                    "name": "Ampath1-eth1",
                    "short_name": "null",
                    "node": "urn:sdx:node:ampath.net:Ampath1",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:ampath.net:Ampath1/1_Ampath2/1",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:ampath.net:Ampath1:40",
                    "name": "Ampath1-eth40",
                    "short_name": "null",
                    "node": "urn:sdx:node:ampath.net:Ampath1",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:port:sax.net:Sax01:40",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:ampath.net:Ampath1:50",
                    "name": "Ampath1-eth50",
                    "short_name": "null",
                    "node": "urn:sdx:node:ampath.net:Ampath1",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:ampath.net:Ampath1:2",
                    "name": "Ampath1-eth2",
                    "short_name": "null",
                    "node": "urn:sdx:node:ampath.net:Ampath1",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:ampath.net:Ampath1/2_Ampath3/2",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
            ],
            "private_attributes": [],
        },
        {
            "id": "urn:sdx:node:sax.net:Sax01",
            "name": "Sax01",
            "short_name": "null",
            "location": {
                "address": "Fortaleza",
                "latitude": -3,
                "longitude": -40,
                "iso3166_2_lvl4": "BR-CE",
            },
            "ports": [
                {
                    "id": "urn:sdx:port:sax.net:Sax01:41",
                    "name": "Sax01-eth41",
                    "short_name": "null",
                    "node": "urn:sdx:node:sax.net:Sax01",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:port:tenet.ac.za:Tenet01:41",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:sax.net:Sax01:1",
                    "name": "Sax01-eth1",
                    "short_name": "null",
                    "node": "urn:sdx:node:sax.net:Sax01",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:sax.net:Sax01/1_Sax02/1",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:sax.net:Sax01:40",
                    "name": "Sax01-eth40",
                    "short_name": "null",
                    "node": "urn:sdx:node:sax.net:Sax01",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:port:ampath.net:Ampath1:40",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:sax.net:Sax01:50",
                    "name": "Sax01-eth50",
                    "short_name": "null",
                    "node": "urn:sdx:node:sax.net:Sax01",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
            ],
            "private_attributes": [],
        },
        {
            "id": "urn:sdx:node:sax.net:Sax02",
            "name": "Sax02",
            "short_name": "null",
            "location": {
                "address": "Fortaleza",
                "latitude": -3,
                "longitude": -20,
                "iso3166_2_lvl4": "BR-CE",
            },
            "ports": [
                {
                    "id": "urn:sdx:port:sax.net:Sax02:41",
                    "name": "Sax02-eth41",
                    "short_name": "null",
                    "node": "urn:sdx:node:sax.net:Sax02",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:port:tenet.ac.za:Tenet02:41",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:sax.net:Sax02:1",
                    "name": "Sax02-eth1",
                    "short_name": "null",
                    "node": "urn:sdx:node:sax.net:Sax02",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:sax.net:Sax01/1_Sax02/1",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:sax.net:Sax02:40",
                    "name": "Sax02-eth40",
                    "short_name": "null",
                    "node": "urn:sdx:node:sax.net:Sax02",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:port:ampath.net:Ampath2:40",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:sax.net:Sax02:50",
                    "name": "Sax02-eth50",
                    "short_name": "null",
                    "node": "urn:sdx:node:sax.net:Sax02",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
            ],
            "private_attributes": [],
        },
        {
            "id": "urn:sdx:node:tenet.ac.za:Tenet02",
            "name": "Tenet02",
            "short_name": "null",
            "location": {
                "address": "Johanesburgo",
                "latitude": -26,
                "longitude": 28,
                "iso3166_2_lvl4": "ZA-GP",
            },
            "ports": [
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet02:41",
                    "name": "Tenet02-eth41",
                    "short_name": "null",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet02",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:port:sax.net:Sax02:41",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet02:1",
                    "name": "Tenet02-eth1",
                    "short_name": "null",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet02",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:tenet.ac.za:Tenet01/1_Tenet02/1",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet02:50",
                    "name": "Tenet02-eth50",
                    "short_name": "null",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet02",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
            ],
            "private_attributes": [],
        },
        {
            "id": "urn:sdx:node:tenet.ac.za:Tenet03",
            "name": "Tenet03",
            "short_name": "null",
            "location": {
                "address": "EastLondon",
                "latitude": -33,
                "longitude": 27,
                "iso3166_2_lvl4": "ZA-EC",
            },
            "ports": [
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet03:50",
                    "name": "Tenet03-eth50",
                    "short_name": "null",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet03",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet03:2",
                    "name": "Tenet03-eth2",
                    "short_name": "null",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet03",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:tenet.ac.za:Tenet01/2_Tenet03/2",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
            ],
            "private_attributes": [],
        },
        {
            "id": "urn:sdx:node:tenet.ac.za:Tenet01",
            "name": "Tenet01",
            "short_name": "null",
            "location": {
                "address": "CapeTown",
                "latitude": -33,
                "longitude": 18,
                "iso3166_2_lvl4": "ZA-WC",
            },
            "ports": [
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet01:41",
                    "name": "Tenet01-eth41",
                    "short_name": "null",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet01",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:port:sax.net:Sax01:41",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet01:1",
                    "name": "Tenet01-eth1",
                    "short_name": "null",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet01",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:tenet.ac.za:Tenet01/1_Tenet02/1",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet01:2",
                    "name": "Tenet01-eth2",
                    "short_name": "null",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet01",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "urn:sdx:link:tenet.ac.za:Tenet01/2_Tenet03/2",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
                {
                    "id": "urn:sdx:port:tenet.ac.za:Tenet01:50",
                    "name": "Tenet01-eth50",
                    "short_name": "null",
                    "node": "urn:sdx:node:tenet.ac.za:Tenet01",
                    "vlan_range": "null",
                    "status": "up",
                    "state": "enabled",
                    "nni": "",
                    "type": "10GE",
                    "services": {
                        "l2vpn_ptp": {"vlan_range": [[1, 4095]]},
                        "l2vpn_ptmp": {},
                        "monitoring_capability": "null",
                        "owner": "null",
                        "private_attributes": "null",
                        "provisioning_system": "null",
                        "provisioning_url": "null",
                        "vendor": "null",
                    },
                    "private_attributes": "null",
                },
            ],
            "private_attributes": [],
        },
    ],
    "links": [
        {
            "id": "urn:sdx:link:interdomain:ampath.net:Ampath1:40:sax.net:Sax01:40",
            "name": "Ampath1-eth40--Sax01-eth40",
            "short_name": "null",
            "ports": [
                "urn:sdx:port:ampath.net:Ampath1:40",
                "urn:sdx:port:sax.net:Sax01:40",
            ],
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 100,
            "status": "up",
            "state": "enabled",
            "private_attributes": "null",
            "timestamp": "null",
            "measurement_period": "null",
        },
        {
            "id": "urn:sdx:link:interdomain:ampath.net:Ampath2:40:sax.net:Sax02:40",
            "name": "Ampath2-eth40--Sax02-eth40",
            "short_name": "null",
            "ports": [
                "urn:sdx:port:ampath.net:Ampath2:40",
                "urn:sdx:port:sax.net:Sax02:40",
            ],
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 100,
            "status": "up",
            "state": "enabled",
            "private_attributes": "null",
            "timestamp": "null",
            "measurement_period": "null",
        },
        {
            "id": "urn:sdx:link:interdomain:sax.net:Sax02:41:tenet.ac.za:Tenet02:41",
            "name": "Sax02-eth41--Tenet02-eth41",
            "short_name": "null",
            "ports": [
                "urn:sdx:port:sax.net:Sax02:41",
                "urn:sdx:port:tenet.ac.za:Tenet02:41",
            ],
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 100,
            "status": "up",
            "state": "enabled",
            "private_attributes": "null",
            "timestamp": "null",
            "measurement_period": "null",
        },
        {
            "id": "urn:sdx:link:interdomain:sax.net:Sax01:41:tenet.ac.za:Tenet01:41",
            "name": "Sax01-eth41--Tenet01-eth41",
            "short_name": "null",
            "ports": [
                "urn:sdx:port:sax.net:Sax01:41",
                "urn:sdx:port:tenet.ac.za:Tenet01:41",
            ],
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 100,
            "status": "up",
            "state": "enabled",
            "private_attributes": "null",
            "timestamp": "null",
            "measurement_period": "null",
        },
        {
            "id": "urn:sdx:link:ampath.net:Ampath2/3_Ampath3/3",
            "name": "Ampath2/3_Ampath3/3",
            "short_name": "null",
            "ports": [
                "urn:sdx:port:ampath.net:Ampath2:3",
                "urn:sdx:port:ampath.net:Ampath3:3",
            ],
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 0,
            "status": "up",
            "state": "enabled",
            "private_attributes": "null",
            "timestamp": "null",
            "measurement_period": "null",
        },
        {
            "id": "urn:sdx:link:ampath.net:Ampath1/2_Ampath3/2",
            "name": "Ampath1/2_Ampath3/2",
            "short_name": "null",
            "ports": [
                "urn:sdx:port:ampath.net:Ampath1:2",
                "urn:sdx:port:ampath.net:Ampath3:2",
            ],
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 0,
            "status": "up",
            "state": "enabled",
            "private_attributes": "null",
            "timestamp": "null",
            "measurement_period": "null",
        },
        {
            "id": "urn:sdx:link:ampath.net:Ampath1/1_Ampath2/1",
            "name": "Ampath1/1_Ampath2/1",
            "short_name": "null",
            "ports": [
                "urn:sdx:port:ampath.net:Ampath1:1",
                "urn:sdx:port:ampath.net:Ampath2:1",
            ],
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 0,
            "status": "up",
            "state": "enabled",
            "private_attributes": "null",
            "timestamp": "null",
            "measurement_period": "null",
        },
        {
            "id": "urn:sdx:link:sax.net:Sax01/1_Sax02/1",
            "name": "Sax01/1_Sax02/1",
            "short_name": "null",
            "ports": ["urn:sdx:port:sax.net:Sax01:1", "urn:sdx:port:sax.net:Sax02:1"],
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 0,
            "status": "up",
            "state": "enabled",
            "private_attributes": "null",
            "timestamp": "null",
            "measurement_period": "null",
        },
        {
            "id": "urn:sdx:link:tenet.ac.za:Tenet01/1_Tenet02/1",
            "name": "Tenet01/1_Tenet02/1",
            "short_name": "null",
            "ports": [
                "urn:sdx:port:tenet.ac.za:Tenet01:1",
                "urn:sdx:port:tenet.ac.za:Tenet02:1",
            ],
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 0,
            "status": "up",
            "state": "enabled",
            "private_attributes": "null",
            "timestamp": "null",
            "measurement_period": "null",
        },
        {
            "id": "urn:sdx:link:tenet.ac.za:Tenet01/2_Tenet03/2",
            "name": "Tenet01/2_Tenet03/2",
            "short_name": "null",
            "ports": [
                "urn:sdx:port:tenet.ac.za:Tenet01:2",
                "urn:sdx:port:tenet.ac.za:Tenet03:2",
            ],
            "bandwidth": 10,
            "residual_bandwidth": 100,
            "latency": 0,
            "packet_loss": 0,
            "availability": 0,
            "status": "up",
            "state": "enabled",
            "private_attributes": "null",
            "timestamp": "null",
            "measurement_period": "null",
        },
    ],
    "private_attributes": "null",
}
